# .github/workflows/ci.yml dosyasının çözülen hali
steps:
  - name: Checkout code
    uses: actions/checkout@v2
  - name: Set up Node.js
    uses: actions/setup-node@v2
    with:
      node-version: '14'
  - name: Install dependencies
    run: npm ci  # Daha iyi bir yöntem olan npm ci kullanıldı
  - name: Run tests
    run: npm test
